GET http://ds4.dest/sap/opu/odata/sap/API_INBOUND_DELIVERY_SRV;v=2/A_InbDeliveryHeader?$expand=to_DeliveryDocumentPartner/to_Address&$format=json
Content-Type: application/json
X-CSRF-Token: fetch

###
GET http://ds4.dest/sap/opu/odata/sap/API_INBOUND_DELIVERY_SRV;v=2/A_InbDeliveryHeader?$expand=to_DeliveryDocumentItem&$top=1&$format=json
Content-Type: application/json
X-CSRF-Token: fetch

###
GET http://ds4.dest/sap/opu/odata/sap/API_INBOUND_DELIVERY_SRV;v=2/A_InbDeliveryHeader?$expand=to_DeliveryDocumentItem/to_DocumentFlow&$top=1&$format=json
Content-Type: application/json
X-CSRF-Token: fetch

###
GET GET http://ds4.dest/sap/opu/odata/sap/API_INBOUND_DELIVERY_SRV;v=2/$metadata

###
GET http://ds4.dest/sap/opu/odata/sap/API_Product_srv/A_Product('241338')?$expand=to_Description&$format=json


###
GET https://ds4.dest/sap/opu/odata/sap/API_INBOUND_DELIVERY_SRV;v=2/A_InbDeliveryItem(DeliveryDocument='180000001',DeliveryDocumentItem='000030')/to_DeliveryDocumentItemText